"""empty message

Revision ID: b5463e60cfd2
Revises: d518d260a739
Create Date: 2021-06-30 17:00:31.088271

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

revision = 'b5463e60cfd2'
down_revision = 'd518d260a739'
branch_labels = None
depends_on = None

session = Session(bind=op.get_bind())
session.execute('PRAGMA foreign_keys = OFF;')
session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('zip',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.Integer(),
                              existing_nullable=True)
        batch_op.alter_column('lat',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.DECIMAL(),
                              existing_nullable=True)
        batch_op.alter_column('lon',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.DECIMAL(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('lon',
                              existing_type=sa.DECIMAL(),
                              type_=sa.VARCHAR(length=80),
                              existing_nullable=True)
        batch_op.alter_column('lat',
                              existing_type=sa.DECIMAL(),
                              type_=sa.VARCHAR(length=80),
                              existing_nullable=True)
        batch_op.alter_column('zip',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(length=80),
                              existing_nullable=True)

    # ### end Alembic commands ###
