"""empty message

Revision ID: 1dfdfafd3434
Revises: b5463e60cfd2
Create Date: 2021-08-11 08:51:00.045063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1dfdfafd3434'
down_revision = 'b5463e60cfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.Enum('ANDROID', 'IOS', name='platform'), nullable=False,
                                      server_default="IOS"))

        # ### end Alembic commands ###

        def downgrade():
            # ### commands auto generated by Alembic - please adjust! ###
            with op.batch_alter_table('devices', schema=None) as batch_op:
                batch_op.drop_column('platform')

            # ### end Alembic commands ###
