"""empty message

Revision ID: 4c7b8ec09f5b
Revises: 1dfdfafd3434
Create Date: 2021-09-18 16:08:19.964641

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4c7b8ec09f5b'
down_revision = '1dfdfafd3434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('device_name', sa.String(length=80), nullable=False, server_default="Unknown Device"))
        batch_op.add_column(sa.Column('kiosk', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('device_name')
        batch_op.drop_column('kiosk')

    # ### end Alembic commands ###
